namespace Forge.S4.Types {
    public enum UIScreen {
        Unknown = 0,

        MainMenu = 1,
        Tutorial,
        Addon,
        MissionCd,
        NewWorld,
        NewWorld2,
        Singleplayer,
        Multiplayer,
        LoadGame,
        Credits,
        AddonTrojan,
        AddonRoman,
        AddonMayan,
        AddonViking,
        AddonSettle,
        MissionCdRoman,
        MissionCdViking,
        MissionCdMayan,
        MissionCdConfl,
        SingleplayerCampaign,
        SingleplayerDarktribe,
        SingleplayerMapSelectSingle,
        SingleplayerMapSelectMulti,
        SingleplayerMapSelectRandom,
        SingleplayerMapSelectUser,
        SingleplayerLobby,
        MultiplayerMapSelectMulti,
        MultiplayerMapSelectRandom,
        MultiplayerMapSelectUser,
        MultiplayerLobby,
        LoadGameCampaign,
        LoadGameMap,
        LoadGameMultiplayer,
        AfterGameSummary,
        AfterGameDetails,
        Ingame,
        MissionDescription,

        Max
    }

    public enum UIMenu {
        S4GuiUnknown = 0,

        ExtrasSave = UIScreen.Max,
        ExtrasMission,
        ExtrasChatSettings,
        ExtrasQuit,
        SettingsGraphics,
        SettingsAudio,
        SettingsGame,
        SettingsNotifications,
        BuildingsFoundation,
        BuildingsMetal,
        BuildingsFood,
        BuildingsMisc,
        BuildingsMiscDecoSubmenu,
        BuildingsMilitary,
        SettlersSummary,
        SettlersWorkers,
        SettlersSpecialists,
        SettlersSearch,
        GoodsSummary,
        GoodsDistribution,
        GoodsPriority,
        StatisticsWarriors,
        StatisticsLand,
        StatisticsGoods,
        UnitSelectionDonkey,
        UnitSelectionMilitary,
        UnitSelectionSpecialists,
        UnitSelectionVehicles,
        UnitSelectionFerry,
        UnitSelectionTradingVehicle,
        UnitSelectionSubSpells,
        UnitSelectionSubGroupings,
        SelectionSubTrade,
        SelectionSubBuildVehicle,
        SelectionSubBarracks,

        Max // never put anything below this
    };
}
